replicaCount: 1

serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: "REPLACE_WITH_TERRAFORM_OUTPUT_ROLE_ARN"

enableShield: false
enableWaf: false
enableWafv2: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

